#Illegal block preventions
# These are required to be enabled for things like stacked items and 32ks to be prevented.
PreventPlacingIllegalBlocks: true
RemoveIllegalBlockOnPlace: true
RemoveIllegalBlocksOnInteract: true
RemoveIllegalBlocksOnJoin: true
RemoveIllegalBlocksOnInventoryOpen: true
RemoveIllegalBlocksOnDrop: true
RemoveIllegalBlocksOnClick: true
RemoveIllegalBlocksOnPickup: true
RemoveIllegalBlocksOnMove: true
#Remove illegal blocks on chunkload, useful if players have placed a lot of bedrock/other blocks and you want to get rid of it this is automatically disabled on non 1.12.2 versions due to errors.
RemoveALLIllegalBlocksOnCHUNKLOAD: false # Please note this may lower tps slightly (or heavily if players have big stashes)
RemoveIllegalHeadsOnChunkLoad: false # NOT RECOMMENDED TO TURN ON, RAPES TPS!
RevertStackedItems: true
RevertEnchantments: true
RevertSpecificEnchantments: false # Only revert specific enchantments
SpecificEnchantments:
  - "DIG_SPEED" #The name of the enchantment in the spigot api
# Only removes player heads, not mob heads
RemoveIllegalHeads: true
# Check for items every X time may cause lag, disable if you have lag issues
StrictIllegalPrevention: false

#Bugfixes
PreventEndGatewayCrashExploit: true
PreventDispenserCrashExploit: true
PreventSnowBallExploit: true
PreventCraftingRecipeLagExploit: true
CraftingRecipeDelay: 5 # in ticks
# Patches coordinate exploit for teleportation commands such as /tpa, /home ASWELL as respawn exploits (such as finding location from bed respawn point) Works by vanishing the player for x ticks before teleporting.
PreventTeleportCoordExploit: true
TeleportVanishTime: 10 # in ticks
PreventDestroyingEndPortals: true
PreventPortalTraps: false
# These are automatically disabled on non 1.12.2 versions due to errors.
FillInBedrockFloor: true
FillInBedrockRoof: true
#
PreventGoingBelowBedrockFloor: true
DisableAllElytras: false
DisableWithers: false
RemoveAllWitherSkulls: false
DisableExplosions: false
FixChatcoIgnoreBug: true
# Attempt to prevent chunk bans/fps lag.
# Automatically disabled in non 1.12 due to a shit ton of errors
PreventChunkBan: true
MaxEnchantmentTablePerChunk: 16
MaxEnderchestPerChunk: 64
MaxContainerPerChunk: 1000
MaxSignPerChunk: 100
MaxSlimePerChunk: 128
MaxBeaconPerChunk: 32
#
# Antispam time in seconds
PreventSpam: true
# Global limit
AntiSpamTime: 1
# How many messages should we allow to send in x seconds (converted to ticks)
AntiSpamCheckTime: 30
AntiSpamMessagesPerTime: 10 # ~1 message every 3 seconds if constantly spamming
AntiSpamWordTime: 60
AntiSpamLinkTime: 300
CharacterLimit: 128
PreventUnicodeDot: true
#
# Removes entitys or players if "invalid", not sure if this works. Seems too simple. But again, mojang is retarded.
ExperimentalGodModePatch: true
PreventCommandSign: true
# Disable the 1.16 fish from spawning, there is a shit ton of them that spawn and this can cause a ton of lag, automatically disabled in 1.12
DisableFish: true
# Prevent massive sand chunks from killing the server, prevents any falling blocks from falling if there is more than 50 falling blocks in a chunk
LimitFallingBlocks: true
FallingBlockLimit: 50 # Max in a chunk
# Prevent having a shit ton of exp bottles in one chunk then loading it to kill the server
LimitExpBottles: true
ExpBottleLimit: 25 # Max in a chunk, doesn't limit the actual xp orbs.
# Prevent projectiles such as xp bottles and snowballs from going through portals, this can cause a shit ton of lag especially if there is new chunks on the other end, this wont prevent mobs or items
PreventProjectilesFromGoingThroughPortals: true

#Dupe preventions
DisableChestsOnDonkeys: false
PreventDonkeysFromGoingThroughPortals: false
# Not sure if this works, please try it
ExperimentalDupePatch: true
# I don't know if this works, someone on discord said I should prevent the mobs from despawning if they are 500 blocks near a player.
# Automatically disabled in non 1.12 because it causes a SHIT ton of mobs to spawn: https://i.imgur.com/f691cep.png and disabled by default in the config because a shit ton of enderman spawn
ExperimentalDupePatch2: false

# Other options
# If the server is running a version higher than 1.12.2 there will be a shit ton of errors for some config options. It is not recommended to enable this unless you know they work.
OverideConfigChanges: false
MaskKickMessages: false
KickMessage: "&6You have lost connection to the server"
PreventSpamKick: false
Preventlinks: false # Code by John200410, edited by moomoo
Replace@: false
JoinLeaveMessages: false
ConnectionMsgsOnByDefault: true # /toggleconnectionmsgs
JoinMessage: "&7%player% joined the game."
LeaveMessage: "&7%player% left the game."
# COMMAND WHITELIST
# This will make it pretty much impossible to find your plugins as only the commands you specify will be able to work. Any other commands will show "Bad command. Type /help for all commands."
CommandWhitelist: false
AllowOPStobypass: true
CommandsWhitelisted:
  - /help
  - /msg
  - /kill
  - /discord
  - /togglechat
  - /toggletells
  - /ignore
  - /ignorelist
  - /toggledeathmsg
  - /stats
  - /tps
  - /w
  - /m
  - /t
  - /pm
  - /tell
  - /whisper
  - /r
  - /reply

BannedWords:
  - "what's 2+2"

# Specific Elytra speed settings for ONLY NEW and OLD chunks (set nocheatplus elytra settings to 999999)
# Disable by setting to 999999
ElytraOldChunkSpeed: 1.81 # 130km/h
ElytraNewChunkSpeed: 1.81 # 130km/h

# Burst elytra speed settings, if the tps is above the amount it will use these settings.
EnableBursting: true
ElytraBurstOldChunkSpeed: 5
ElytraBurstOldChunkTPS: 18
ElytraBurstNewChunkSpeed: 3.12 # 223km/h
ElytraBurstNewChunkTPS: 19

LimitRenderDistanceBasedOnTPS: false
# Radius for chunks when the server is below your tps amount
NewChunkRadius: 3
OldChunkRadius: 3
# Radius for chunks when the server is above your tps amount
NewChunkBurstRadius: 3
OldChunkBurstRadius: 6
# If the server is below this tps it will use the non burst radius.
NewChunkBurstTPS: 19
OldChunkBurstTPS: 18

# Show some info on the actionbar while flying with elytra.
ElytraActionBar: true

# Patches the future/rusherhack/kamiblue 2b2t elytra fly exploit
PatchPacketElytraFly: false
# Recommended to not go lower as there could be false positives.
MaxElytraOpensPer10Seconds: 25 # Will only allow players to go about 85km/h on kami blue, and won't even work on rusherhack.

# Patch future/rusher packet fly
PreventPacketFly: true
# Max teleport packets per 10 seconds, this is how the packet fly works, 25 is usually fine, if you go lower players may get stuck.
MaxTeleportPacketsPer10Seconds: 25
LogPacketFlyEvents: false

# Patch futureclient boat fly exploit
# This does not affect boats at all! Even on land.
BoatflyPatch: true
MaxEntityPacketsPer10Seconds: 15
LogBoatFlyEvents: true

# Don't enable this, its shit
# This affects boats on land and other things.
LegacyBoatFlyPatch: false

#List of banned blocks.
#WARNING: ADDING MOB SPAWNER TO THIS LIST WHILE HAVING RemoveALLIllegalBlocksOnCHUNKLOAD ENABLED WILL REMOVE ALL MOB SPAWNERS IN YOUR WORLD.
#You can also add non blocks and they should get removed aswell.
BANNED_BLOCKS:
  - BEDROCK
  - BARRIER
  - COMMAND
  - STRUCTURE_BLOCK
  - MONSTER_EGG

OnlyRevertStacksForCertainItems: false
RevertStackedItemsList:
  - TOTEM
#The item banned blocks are replaced with.
Replacement_Item: STONE

# Redstone
# Will kick player if they hit lever LeverLimitAmount times within LeverLimitTime
RateLimitLevers: false
LeverLimitAmount: 5
LeverLimitTime: 40
RateLimitKick: false
RateLimitKickMsg: "&cLevers are currently disabled due to an exploit"

# DISABLE STUFF AT CERTAIN TPS
# SET TO -1 TO ENABLE ALL THE TIME.
Redstone: 16

Elytra: 13
# Removes the elytra from the player's chestplate slot, there is no need to do this as this will make players fall to their death once tps is low.
RemoveElytra: false

Explosions: 17

FallingBlocks: 19

# END OF CONFIG

# No need to mess with these they are meant for my server
# 1b1t options
AllowBreakingBedrock: false
1b1tPlaceBedrock: false
UseSparkhealth: false
nickresetonly: false
5000blocksawaytoteleport: false
# This will only allow walking on the nether roof. Use permission node anarchyexploitfixes.netherroofbypass to bypass
PreventNetherRoof: false
#Enable the shitty 1b1t slow! dupe - 5% chance of duplicating items by punching an item frame.
SlowDupe: false
MakeSpecificCommandsHurtYou: false
HurtCommands:
  - /tpa
DisableNCPGeyser: false
BypassSlots: false