metadata.format.version = "1.1"

[versions]
runpaperversion = "1.20.4"
foliabundle = "1.20.4-R0.1-SNAPSHOT"

[libraries]
paper = "io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT"
folia = "dev.folia:folia-api:1.20.4-R0.1-SNAPSHOT"
paper12 = "com.destroystokyo.paper:paper-api:1.12.2-R0.1-SNAPSHOT"
configmaster = "com.github.thatsmusic99:ConfigurationMaster-API:v2.0.0-rc.1"
bstats = "org.bstats:bstats-bukkit:3.0.2"
caffeineJ17 = "com.github.ben-manes.caffeine:caffeine:3.1.8"
caffeineJ8 = "com.github.ben-manes.caffeine:caffeine:2.9.3"
hikaricp = "com.zaxxer:HikariCP:5.1.0"
xseries = "com.github.cryptomorin:XSeries:9.9.0"
reflections = "org.reflections:reflections:0.10.2"

[plugins]
runpaper = { id = "xyz.jpenilla.run-paper", version = "2.2.2" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
userdev = { id = "io.papermc.paperweight.userdev", version = "1.5.11" }
downgradeJava = { id = "net.raphimc.java-downgrader", version = "1.1.1" }

[bundles]
